# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-49d041e7-ee65-466e-9fa3-6aed037a0a28";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-49d041e7-ee65-466e-9fa3-6aed037a0a28".device =
    "/dev/disk/by-uuid/49d041e7-ee65-466e-9fa3-6aed037a0a28";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3EAD-64AD";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/mnt/DISCO" = {
    device = "/dev/disk/by-uuid/5c120c58-ffea-4ad5-9a59-eeb8ed2b9239";
    fsType = "ext4";
    options = [
      "defaults"
      "x-systemd.automount"
      "x-gvfs-show"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
